### ISSUE TITLE
In Options, why are omitFields and omitCases String -> ... and not List -> ...

### ISSUE THREAD

**Issue by chiroptical** [MercuryTechnologies/moat#21]

**Comment by chessai** [comment]
Ask max t. He should be able to search chat logs with me for why this was decided upon.

**Comment by chiroptical** [comment]
For reference, these issues and PRs are mostly for me to keep track off. No worries if you want to turn off notifications :)

**Comment by chessai** [comment]
I'm interested in seeing improvements to the library, so want to keep notifications on.

I think a new major release should be made after typescript is supported. There have been a number of bugfixes and improvements.

**Comment by chiroptical** [comment]
Nice, and I agree. I think tomorrow afternoon I'll try it with Mercury and see what goes wrong from the TS side.

**Comment by chiroptical** [comment]
Actually this issue makes no sense. `omitFields` is a function which describes what fields to keep or discard
