### ISSUE TITLE
Spliced code not in scope due to `mkName` use

### ISSUE THREAD

**Issue by parsonsmatt** [MercuryTechnologies/moat#4]
Using `mkName` means that Haskell will use *whatever* term is in scope at the splice site for the code in question. If the name is not in scope, then it will complain about the name being out of scope. This can be confusing.

See [this code bit](https://github.com/chessai/moat/blob/master/src/Moat.hs#L1579-L1588) for an example of this pattern.

To fix it, it'd be good to use the ticks to form a fully qualified name, which will work regardless of whether or not the type is imported.

**Comment by chessai** [comment]
Agree. Can I add you and Barry as maintainers to this repo?

**Comment by chessai** [comment]
Actually, can I transfer ownership to mercury? It's admittedly going to be hard for me to maintain this repo going forward. As long as I'm still listed as an author I don't care who owns it. I can still advise on how to do things.

**Comment by chessai** [comment]
> Actually, can I transfer ownership to mercury? It's admittedly going to be hard for me to maintain this repo going forward. As long as I'm still listed as an author I don't care who owns it. I can still advise on how to do things.

cc @MaxGabriel

**Comment by parsonsmatt** [comment]
Yeah sure thing! I'd be happy to accept maintainership.

**Comment by chessai** [comment]
When I try to transfer ownership, I get 'MercuryTechnologies/moat already exists and You don’t have the permission to create public repositories on MercuryTechnologies'. Can you delete your fork so I can transfer ownership?

**Comment by parsonsmatt** [comment]
We are apparently using that fork instead of this repo. I'm going to put together a PR for our collected changes, get it merged upstream, and then we can do the transfer. Does that sound good to you?

**Comment by chessai** [comment]
That sounds good to me. Thanks

**Comment by chiroptical** [comment]
Transferred to @chiroptical for now. Will get this ultimately transferred to Mercury.
