### ISSUE TITLE
Transfer repository to Mercury Technologies

### ISSUE THREAD

**Issue by chiroptical** [MercuryTechnologies/moat#5]
Hey @chessai, you should be able to transfer ownership now.

**Comment by chessai** [comment]
I tried, I get an error saying that MercuryTechnologies already has a repository in the chessai/moat network, and that I don't have permission to create repositories in MercuryTechnologies.

**Comment by chiroptical** [comment]
I was hoping just renaming it would work. I'll all of our changes into this repo and ping you when I am done.

**Comment by chiroptical** [comment]
Okay, to streamline this. Just transfer it to @chiroptical and I'll transfer it to Mercury when everything is done. No reason to bother you will all this activity.

**Comment by chiroptical** [comment]
@chessai just bumping this. I deleted my fork

**Comment by chessai** [comment]
Repository transfer to chiroptical requested

**Comment by chiroptical** [comment]
Perfect. Thanks!
